# Generated by Django 5.1.1 on 2024-10-19 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('instituicao', models.CharField(max_length=100)),
                ('data_aula', models.DateField()),
                ('disciplina', models.CharField(max_length=40)),
                ('conteudo', models.TextField()),
            ],
            options={
                'db_table': 'aula',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('apelido', models.CharField(max_length=20)),
                ('perfil', models.CharField(choices=[('I', 'Instrutor'), ('P', 'Participante')], max_length=1)),
                ('password', models.CharField(max_length=256)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='AnexoAula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('A', 'Arquivo'), ('F', 'Foto'), ('S', 'Audio')], max_length=1)),
                ('extensao', models.CharField(choices=[('P', 'PDF'), ('J', 'JPG'), ('W', 'WAVE')], max_length=3, null=True)),
                ('caminho_anexo', models.CharField(max_length=100)),
                ('aula', models.ForeignKey(db_column='id_aula', on_delete=django.db.models.deletion.DO_NOTHING, to='core.aula')),
            ],
            options={
                'db_table': 'anexo_aula',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('data_comentario', models.DateField()),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('P', 'Propria'), ('O', 'Opiniao')], max_length=1)),
                ('aula', models.ForeignKey(db_column='id_aula', on_delete=django.db.models.deletion.DO_NOTHING, to='core.aula')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
        migrations.CreateModel(
            name='AnexoComentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('A', 'Arquivo'), ('F', 'Foto'), ('S', 'Audio')], max_length=1)),
                ('extensao', models.CharField(choices=[('P', 'PDF'), ('J', 'JPG'), ('W', 'WAVE')], max_length=3, null=True)),
                ('caminho_anexo', models.CharField(max_length=100)),
                ('comentario', models.ForeignKey(db_column='id_comentario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.comentario')),
            ],
            options={
                'db_table': 'anexo_comentario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioAula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('aula', models.ForeignKey(db_column='id_aula', on_delete=django.db.models.deletion.DO_NOTHING, to='core.aula')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_aula',
            },
        ),
    ]
